### ISSUE TITLE
rpn_loss_box = nan error when training on own dataset

### ISSUE THREAD

**Issue by BeSlower** [CharlesShang/TFFRCNN#10]
Hi,

When I train on my own data, I got issue as follows. Could you help me to figure out what's going on here?

Thanks.
```
image: 69814.jpg iter: 80 / 70000, total loss: 0.3977, rpn_loss_cls: 0.1209, rpn_loss_box: 0.1309, loss_cls: 0.0813, loss_box: 0.0646, lr: 0.001000
speed: 0.344s / iter
image: 63214.jpg iter: 90 / 70000, total loss: 0.8382, rpn_loss_cls: 0.1620, rpn_loss_box: 0.0919, loss_cls: 0.2161, loss_box: 0.3681, lr: 0.001000
speed: 0.322s / iter
./faster_rcnn/../lib/fast_rcnn/bbox_transform.py:36: RuntimeWarning: invalid value encountered in log
  targets_dw = np.log(gt_widths / ex_widths)
./faster_rcnn/../lib/rpn_msr/proposal_layer_tf.py:184: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((ws >= min_size) & (hs >= min_size))[0]
image: 66306.jpg iter: 100 / 70000, total loss: nan, rpn_loss_cls: 0.6870, rpn_loss_box: nan, loss_cls: 0.4501, loss_box: 0.2214, lr: 0.001000
speed: 0.313s / iter
image: 62335.jpg
Traceback (most recent call last):
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 85, in __call__
    ret = func(*args)
  File "./faster_rcnn/../lib/rpn_msr/proposal_target_layer_tf.py", line 78, in proposal_target_layer
    rois_per_image, _num_classes)
  File "./faster_rcnn/../lib/rpn_msr/proposal_target_layer_tf.py", line 182, in _sample_rois
    rois[:, 1:5], gt_boxes[gt_assignment[keep_inds], :4], labels)
  File "./faster_rcnn/../lib/rpn_msr/proposal_target_layer_tf.py", line 224, in _compute_targets
    targets = bbox_transform(ex_rois, gt_rois)
  File "./faster_rcnn/../lib/fast_rcnn/bbox_transform.py", line 25, in bbox_transform
    format(ex_rois[np.argmin(ex_widths), :], ex_rois[np.argmin(ex_heights), :])
AssertionError: Invalid boxes found: [ 102398.4375     151.5625     285.9375     478.125 ] [ 165.02432251  123.3543396   318.14932251  215.5418396 ]
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed to run py callback pyfunc_2: see error log.
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 396, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 251, in train_model
    cls_prob, bbox_pred, rois =  sess.run(fetches=fetch_list, feed_dict=feed_dict)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_135, _recv_gt_boxes_0, _recv_gt_ishard_0, _recv_dontcare_areas_0, roi-data/PyFunc/input_4)]]

Caused by op u'roi-data/PyFunc', defined at:
  File "./faster_rcnn/train_net.py", line 101, in <module>
    network = get_network(args.network_name)
  File "./faster_rcnn/../lib/networks/factory.py", line 27, in get_network
    return VGGnet_train()
  File "./faster_rcnn/../lib/networks/VGGnet_train.py", line 17, in __init__
    self.setup()
  File "./faster_rcnn/../lib/networks/VGGnet_train.py", line 80, in setup
    .proposal_target_layer(n_classes,name = 'roi-data'))
  File "./faster_rcnn/../lib/networks/network.py", line 27, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "./faster_rcnn/../lib/networks/network.py", line 242, in proposal_target_layer
    [tf.float32,tf.float32,tf.float32,tf.float32,tf.float32])
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 192, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/zhans/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_2: see error log.
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_135, _recv_gt_boxes_0, _recv_gt_ishard_0, _recv_dontcare_areas_0, roi-data/PyFunc/input_4)]]

```

**Comment by CharlesShang** [comment]
I met this problem before. It seems it generates invalid boxes.

**Comment by CharlesShang** [comment]
#23 

> The best practice to prevent invalid boxes is to lower down the stddev (from 0.01 to 0.001) when initializing the rpn_bbox_pred layer.

**Comment by juzhitao** [comment]
how to modify code? there are several stddev , I modify all stddev to 1/10 but the problem is same

**Comment by amirmgh1375** [comment]
its just for dataset annotations.
you should modify the `pascal_voc.py` code as follows :+1: 

`x1 = max(float(bbox.find('xmin').text), 0)`
`y1 = max(float(bbox.find('ymin').text) , 0)`
`x2 = max(float(bbox.find('xmax').text) , 0)`
`y2 = max(float(bbox.find('ymax').text) , 0)`
or  
`x1 = max(float(bbox.find('xmin').text) - 1, 0)`
`y1 = max(float(bbox.find('ymin').text) - 1, 0)`
`x2 = max(float(bbox.find('xmax').text)  - 1, 0)`
`y2 = max(float(bbox.find('ymax').text)  - 1, 0)`
