### ISSUE TITLE
AssertionError: Single batch only

### ISSUE THREAD

**Issue by XChuanLee** [CharlesShang/TFFRCNN#116]
Sorry I just cannot solve this when I run train_net.py using
python ./faster_rcnn/train_net.py --gpu 0 --weights ./data/pretrain_model/VGG_imagenet.npy --imdb voc_2007_trainval --iters 70000 --cfg  ./experiments/cfgs/faster_rcnn_end2end.yml --network VGGnet_train --restore 0  --set EXP_DIR exp_dir
It comes up
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 185, in train_model
    blobs = data_layer.forward()
  File "./faster_rcnn/../lib/roi_data_layer/layer.py", line 73, in forward
    blobs = self._get_next_minibatch()
  File "./faster_rcnn/../lib/roi_data_layer/layer.py", line 69, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "./faster_rcnn/../lib/roi_data_layer/minibatch.py", line 39, in get_minibatch
    assert len(im_scales) == 1, "Single batch only"
AssertionError: Single batch only
Help...

**Comment by ZJiaQi** [comment]
I also met this problem

**Comment by wuhaotju** [comment]
can you help me? i also meet the problem.

**Comment by XChuanLee** [comment]
@wuhaotju NO...sorry about that...
