### ISSUE TITLE
modelpath

### ISSUE THREAD

**Issue by QueenJuliaZxx** [CharlesShang/TFFRCNN#120]
I am a little white,could you tell me where should I put the model and what I should write in madelpath in demo.py,thank you very much!

**Comment by QueenJuliaZxx** [comment]
Solving...
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 401, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 172, in train_model
    raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by bujingdexin** [comment]
Do you solve this question?
