### ISSUE TITLE
train from checpoints

### ISSUE THREAD

**Issue by QueenJuliaZxx** [CharlesShang/TFFRCNN#122]
Hi,I want to train after 160000 iters,how should I use the order?thank you very much!
Mine:
python ./faster_rcnn/train_net.py \
    --gpu 1 \
    --weights ./output/faster_rcnn_end2end_pva_kitti1/kittivoc_train/PVAnet_iter_160000.ckpt \
    --imdb kittivoc_train \
    --iters 160000 \
    --cfg ./experiments/cfgs/faster_rcnn_end2end_pva_kitti1.yml \
    --network PVAnet_train \
    --restore 0
but it cause error:
Loading pretrained model weights from ./output/faster_rcnn_end2end_pva_kitti1/kittivoc_train/PVAnet_iter_160000.ckpt
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 118, in <module>
    restore=bool(int(args.restore)))  #1
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 405, in train_net
    sw.train_model(sess, max_iters, restore=restore)  #restore=true
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 163, in train_model
    raise 'Check your pretrained model {:s}'.format(self.pretrained_model)
TypeError: exceptions must be old-style classes or derived from BaseException, not str

**Comment by HaoWangDL** [comment]
@QueenJuliaZxx Hello ,

I also met this problem. How do you solve it

**Comment by chiyandetaotie** [comment]
@QueenJuliaZxx @HaoWangDL 
Hello,
I have a problem,could you help me?
I interrupted a training (and saved the fixed step model). After two days, I want to continue training in the place where I last interrupted. How to do it?I am a newbie, I hope to answer with the most specific examples, instead of applying the official function.Thanks.

**Comment by pale1018** [comment]
I have the same problem,could you tell me how to fix it? thanks!!@HaoWangDL @chiyandetaotie @CharlesShang @QueenJuliaZxx
