### ISSUE TITLE
Nontype error when run demo and train

### ISSUE THREAD

**Issue by zhufengli** [CharlesShang/TFFRCNN#139]
I have encountered the Nontype error when I run demo and train. I do exactly the same thing in Readme. Can anybody help me solve this problem?

Tensor("data:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/Relu:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/Relu:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/Relu:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/BiasAdd:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("gt_boxes:0", shape=(?, 5), dtype=float32)
Tensor("gt_ishard:0", shape=(?,), dtype=int32)
Tensor("dontcare_areas:0", shape=(?, 4), dtype=float32)
Tensor("im_info:0", shape=(?, 3), dtype=float32)
Tensor("rpn_cls_score/BiasAdd:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_2:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_bbox_pred/BiasAdd:0", shape=(?, ?, ?, 36), dtype=float32)
Tensor("im_info:0", shape=(?, 3), dtype=float32)
Tensor("rpn_rois:0", shape=(?, 5), dtype=float32)
Tensor("gt_boxes:0", shape=(?, 5), dtype=float32)
Tensor("gt_ishard:0", shape=(?,), dtype=int32)
Tensor("dontcare_areas:0", shape=(?, 4), dtype=float32)
Tensor("conv5_3/Relu:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("roi-data/rois:0", shape=(?, 5), dtype=float32)
[<tf.Tensor 'conv5_3/Relu:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'roi-data/rois:0' shape=(?, 5) dtype=float32>]
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 101, in <module>
    network = get_network(args.network_name)
  File "./faster_rcnn/../lib/networks/factory.py", line 29, in get_network
    return VGGnet_train()
  File "./faster_rcnn/../lib/networks/VGGnet_train.py", line 17, in __init__
    self.setup()
  File "./faster_rcnn/../lib/networks/VGGnet_train.py", line 85, in setup
    .fc(4096, name='fc6')
  File "./faster_rcnn/../lib/networks/network.py", line 36, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "./faster_rcnn/../lib/networks/network.py", line 377, in fc
    feed_in, dim = (input, int(input_shape[-1]))
TypeError: __int__ returned non-int (type NoneType)

**Comment by sulpuresshadow** [comment]
lower version of tensorflow may solve it

**Comment by forwardwfg** [comment]
I meet the same problem, are you make it?

**Comment by tjzjp** [comment]
I met the same problem, have you fixed it?

**Comment by Wushangwu** [comment]
> I met the same problem, have you fixed it?

have you fixed this problem？
