### ISSUE TITLE
ImportError: No module named lib.networks.factory

### ISSUE THREAD

**Issue by civilman628** [CharlesShang/TFFRCNN#15]
I can build pass, but when i run demo.py it reports error:

scopeserver@scopephotos:~/RaidDisk/DeepLearning/mwang/tensorflow/TFFRCNN$ python ./faster_rcnn/demo.py  
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
./faster_rcnn
Traceback (most recent call last):
  File "./faster_rcnn/demo.py", line 12, in <module>
    from lib.networks.factory import get_network
**ImportError: No module named lib.networks.factory**

---------------------------------------------

but i can clearly see the folder is there.

**Comment by nikste** [comment]
Just had the same problem, as a quickfix you can add this to your demo.py

```sys.path.append('/path/to/TFFRCNN/')```

**Comment by civilman628** [comment]
thanks, i get new errors:

Traceback (most recent call last):
  File "./faster_rcnn/demo.py", line 15, in <module>
    from lib.networks.factory import get_network
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/TFFRCNN/lib/__init__.py", line 1, in <module>
    import fast_rcnn
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/TFFRCNN/lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/TFFRCNN/lib/fast_rcnn/train.py", line 15, in <module>
    from .nms_wrapper import nms_wrapper
  File "/home/scopeserver/RaidDisk/DeepLearning/mwang/TFFRCNN/lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from ..nms.gpu_nms import gpu_nms
**ImportError: No module named gpu_nms**

**Comment by civilman628** [comment]
i need check path one by one?

**Comment by jackytu256** [comment]
Hi civilman,
I just tried to copy demo file to the root of TFFRCNN and then python it to get the result of demo.

**Comment by 714586886** [comment]
hi @civilman628 i meet the same error as you 
ImportError: No module named lib.networks.factory
how to fix it?

**Comment by civilman628** [comment]
@714586886 copy demo file to the root of TFFRCNN and then python it to get the result of demo

**Comment by vinayakarannil** [comment]
still facing the same issue...i copied demo  file to the root of TFFRCNN, now facing different issue

Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    from lib.networks.factory import get_network
  File "../lib/__init__.py", line 1, in <module>
    import fast_rcnn
ImportError: No module named 'fast_rcnn'

i think there is some issues with the the fast_rcnn folder of lib.

**Comment by Rasec8401** [comment]
i just executed this on the terminal.
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
and it worked

**Comment by a3551571** [comment]
I met the same issue with you.Did you solve the problem?
Can you show me how to solve it?@vinayakkailas 
Thank you very much!

**Comment by kxhit** [comment]
@vinayakkailas 
Hi I met the same problem. `ImportError: No module named 'fast_rcnn'` Did you solve this problem? Thank you!

**Comment by zengjingcheng** [comment]
I first add sys.path.append('/.../TFFRCNN/')as @nikste  said
then  I # the fast_rcnn in _init_.py
then I had another problem:

current path is /home/zjc/TFFRCNN/faster_rcnn/demo.py
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    raise IOError(('Error: Model not found.\n'))
OSError: Error: Model not found.

**Comment by HaoWangDL** [comment]
@kxhit  Hi I met the same problem. ImportError: No module named 'fast_rcnn' Did you solve this problem?  Tks

**Comment by HaoWangDL** [comment]
@vinayakkailas Hi I met the same problem. ImportError: No module named 'fast_rcnn' Did you solve this problem? Tks

**Comment by HaoWangDL** [comment]
@civilman628 Hi I met the same problem. ImportError: No module named 'fast_rcnn' Did you solve this problem? Tks

**Comment by hxf930620** [comment]
@HaoWangDL 你解决问题了吗，qq：769598959，加qq交流

**Comment by lixiaorui4444** [comment]
from . import fast_rcnn 加到  fast_rcnn里面的__init__里面，解决好不到fast__rcnn的问题

**Comment by lixiaorui4444** [comment]
please add   ' from . import fast_rcnn'      to    __init__  of   fast_rcnn   ,and  I got the problem —— 'no moudle found fast__rcnn'  .
