### ISSUE TITLE
Key Error : Max_overlap

### ISSUE THREAD

**Issue by Esugi8** [CharlesShang/TFFRCNN#20]
I got ResourceExhaustedError when running train_net.py with original PASCAL VOC 2007,
so I reduced the number of Images and Annotations to 1000.
Then I tried to run train_net.py again, and got an error below.

What should I do for solving this error?
Could you please let me know any solution for this?

Computing bounding-box regression targets...
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 394, in train_net
    sw = SolverWrapper(sess, network, imdb, roidb, output_dir, logdir= log_dir, pretrained_model=pretrained_model)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 44, in __init__
    self.bbox_means, self.bbox_stds = rdl_roidb.add_bbox_regression_targets(roidb)
  File "./faster_rcnn/../lib/roi_data_layer/roidb.py", line 65, in add_bbox_regression_targets
    max_overlaps = roidb[im_i]['max_overlaps']
**KeyError: 'max_overlaps'**

**Comment by CharlesShang** [comment]
Hi, @Esugi8 Did you figure out this problem? 
ResourceExhaustedError sounds like your GPU does not have enough memories. 
You can try to set `TRAIN.SCALES` to a small number, like 400.

**Comment by liu09114** [comment]
did you solve it?

**Comment by AuroraLHT** [comment]
try clean up the roidb cache file in $TFFRCNN/data/cache.  It works for me to solve the 'max_overlaps' problem.
