### ISSUE TITLE
Resnet101 error

### ISSUE THREAD

**Issue by jwnsu** [CharlesShang/TFFRCNN#22]
Today I tried Resnet101 in CharlesShang/TFFRCNN (pulled latest codes as of
today from master branch), saw following error in training:
--------
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 397, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 108, in train_model
    self.net.build_loss(ohem=cfg.TRAIN.OHEM)
  File "./faster_rcnn/../lib/networks/network.py", line 446, in build_loss
    cls_score = self.get_output('cls_score') # (R, C+1)
  File "./faster_rcnn/../lib/networks/network.py", line 80, in get_output
    raise KeyError('Unknown layer name fed: %s'%layer)
KeyError: 'Unknown layer name fed: cls_score'

In original https://github.com/miraclebiu/TFFRCN_resnet50, resnet101 works fine (though no accuracy improvement).

**Comment by jwnsu** [comment]
fixed by modifying resnet101 network definition.

**Comment by pngingg** [comment]
@jwnsu 
Hi, I have the same problem. Can you tell me where did you modify? Thanks!
