### ISSUE TITLE
Error on Training on Pascal VOC 2007

### ISSUE THREAD

**Issue by Albert0147** [CharlesShang/TFFRCNN#39]
I have got an error when I train on Pascal VOC 2007 according to the README.md:

 ```
Traceback (most recent call last):
 File "./faster_rcnn/train_net.py", line 109, in <module>
     restore=bool(int(args.restore)))
 File "./faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
     sw.train_model(sess, max_iters, restore=restore)
 File "./faster_rcnn/../lib/fast_rcnn/train.py", line 171, in train_model
     raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
 AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
```

I don't know what it exactly means  and what I should  do

**Comment by Albert0147** [comment]
I have solved the problem by add --restore 0,but then some other errors occur,by the way,I run it on GTX1060 6GB
the error likes:

```
> 2017-03-21 20:51:15.764170: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 117.19MiB.  See logs for memory state.
> 2017-03-21 20:51:15.764200: W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[1,64,600,800]
> Traceback (most recent call last):
>   File "./faster_rcnn/train_net.py", line 109, in <module>
>     restore=bool(int(args.restore)))
>   File "./faster_rcnn/../lib/fast_rcnn/train.py", line 401, in train_net
>     sw.train_model(sess, max_iters, restore=restore)
>   File "./faster_rcnn/../lib/fast_rcnn/train.py", line 256, in train_model
>     cls_prob, bbox_pred, rois =  sess.run(fetches=fetch_list, feed_dict=feed_dict)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
>     run_metadata_ptr)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
>     feed_dict_string, options, run_metadata)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
>     target_list, options, run_metadata)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,64,600,800]
> 	 [[Node: conv1_2/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_1/Relu, conv1_2/weights/read)]]
> 	 [[Node: gradients/TopKV2_grad/Reshape_2/_195 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_435_gradients/TopKV2_grad/Reshape_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
> 
> Caused by op u'conv1_2/Conv2D', defined at:
>   File "./faster_rcnn/train_net.py", line 101, in <module>
>     network = get_network(args.network_name)
>   File "./faster_rcnn/../lib/networks/factory.py", line 29, in get_network
>     return VGGnet_train()
>   File "./faster_rcnn/../lib/networks/VGGnet_train.py", line 17, in __init__
>     self.setup()
>   File "./faster_rcnn/../lib/networks/VGGnet_train.py", line 29, in setup
>     .conv(3, 3, 64, 1, 1, name='conv1_2', trainable=False)
>   File "./faster_rcnn/../lib/networks/network.py", line 36, in layer_decorated
>     layer_output = op(self, layer_input, *args, **kwargs)
>   File "./faster_rcnn/../lib/networks/network.py", line 146, in conv
>     conv = convolve(input, kernel)
>   File "./faster_rcnn/../lib/networks/network.py", line 136, in <lambda>
>     convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
>     data_format=data_format, name=name)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
>     op_def=op_def)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2402, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/home/albert/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
>     self._traceback = _extract_stack()
> 
> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,64,600,800]
> 	 [[Node: conv1_2/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_1/Relu, conv1_2/weights/read)]]
> 	 [[Node: gradients/TopKV2_grad/Reshape_2/_195 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_435_gradients/TopKV2_grad/Reshape_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by yanxp** [comment]
@Albert0147 hello,have you solved the problem?

**Comment by Albert0147** [comment]
@yanxp I found that the gpu usage never goes over 50% and don't know why and how to do. I have just tried vgg model on pytorch instead of tf.

**Comment by hiz0ey** [comment]
@Albert0147 @yanxp @CharlesShang @civilman628 I met the same problom as well, does anyone have solved this problem?

My developing environment is below
Tensorflow：1.0.1
GPU/CPU：GPU GeForce GTX 1070/PCIe/SSE2 8GB
Python: 2.7.13 

UPDATE:
I transfered the training on PASCAL VOC to Resnet50, and it worked.

**Comment by Yc174** [comment]
@Albert0147 @hiz0ey @yanxp @CharlesShang I have the same problem,and I set restore=0,but my computer will restart soon and this killed my system. This also made my hard disk broken and I had to reinstall my system...So why I set restore=0 and then the program distory my computer?

**Comment by Albert0147** [comment]
@hiz0ey Me too,I train resnet50 on tensorflow and vgg16 on pytorch

**Comment by Albert0147** [comment]
@Yc174 I don't know, I have always set restore to 0...

**Comment by Yc174** [comment]
@Albert0147 @hiz0ey Now I have solved this problem and found that downtime is because the GPU power consumption is too large, the power did not keep up.So I changed my power from 500W to 600W,and it worked.
