### ISSUE TITLE
failed to load _roi_pooling_module

### ISSUE THREAD

**Issue by Jiakui** [CharlesShang/TFFRCNN#65]
>>> _roi_pooling_module = tf.load_op_library("/media/veilytech/Data/TFFRCNN/lib/roi_pooling_layer/roi_pooling.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /media/veilytech/Data/TFFRCNN/lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_

# I am using tensorflow 1.1.0-rc2.

**Comment by hiz0ey** [comment]
Try tensorflow 1.0.1, I did not meet this error.

**Comment by cdathuraliya** [comment]
See the changes in https://github.com/cdathuraliya/TFFRCNN/commit/89f59cee7b225307ee9eda9e9a0f66f6de8b52b2
