### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ndarray'

### ISSUE THREAD

**Issue by Hub-Tian** [CharlesShang/TFFRCNN#82]
Computing bounding-box regression targets...
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 398, in train_net
    sw = SolverWrapper(sess, network, imdb, roidb, output_dir, logdir= log_dir, pretrained_model=pretrained_model)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 44, in __init__
    self.bbox_means, self.bbox_stds = rdl_roidb.add_bbox_regression_targets(roidb)
  File "./faster_rcnn/../lib/roi_data_layer/roidb.py", line 68, in add_bbox_regression_targets
    _compute_targets(rois, max_overlaps, max_classes)
  File "./faster_rcnn/../lib/roi_data_layer/roidb.py", line 147, in _compute_targets
    targets[ex_inds, 1:] = bbox_transform(ex_rois, gt_rois)
  File "./faster_rcnn/../lib/fast_rcnn/bbox_transform.py", line 23, in bbox_transform
    assert np.min(ex_widths) > 0.1 and np.min(ex_heights) > 0.1, \
  File "/usr/lib64/python2.7/site-packages/numpy/core/fromnumeric.py", line 2363, in amin
    if type(a) is not mu.ndarray:
AttributeError: 'module' object has no attribute 'ndarray'
./experiments/scripts/faster_rcnn_voc_resnet.sh: line 9:  5831 Segmentation fault      (core dumped) python ./faster_rcnn/train_net.py --gpu 0 --weights ./data/pretrain_model/Resnet50.npy --imdb voc_2007_trainval --iters 160000 --cfg ./experiments/cfgs/faster_rcnn_end2end_resnet.yml --network Resnet101_train --restore 0

I am using K80Gpu with cuda8.0 and python2.7. How can I handle this problem?

**Comment by louisly** [comment]
i have met the same error, have you solve the problem ?
