### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (KITTI)

### ISSUE THREAD

**Issue by cdathuraliya** [CharlesShang/TFFRCNN#83]
Hi,

I'm getting below error when I try to train on KITTI dataset. Training happens normally on PASCAL VOC. Any help would be much appreciated.
```
...
assign pretrain model biases to conv2_2
assign pretrain model weights to conv2_1
assign pretrain model biases to conv2_1
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 271, in train_model
    bbox_pred = bbox_pred * np.tile(self.bbox_stds, (bbox_pred.shape[0], 1)) + \
ValueError: operands could not be broadcast together with shapes (128,84) (128,16)
```

- TensorFlow 1.1.0 GPU

**Comment by cdathuraliya** [comment]
Same as https://github.com/cdathuraliya/Faster-RCNN_TF/commit/c3f8f57976a7341c14bbaef6eb70bd3cbedb3d94 I had to manually update `__C.NCLASSES` value in `lib/fast_rcnn/config.py` to 4 as a workaround. Also check https://github.com/smallcorgi/Faster-RCNN_TF/issues/60#issuecomment-305630222

**Comment by LiuzcEECS** [comment]
Manually changing `.yml` files does solve the problem.

**Comment by Super-jm** [comment]
have you sloved this problem? i met the same question as you. Could you give me some advice?Thank you very much.
