### ISSUE TITLE
Loading trained model

### ISSUE THREAD

**Issue by leifsyliongka** [CharlesShang/TFFRCNN#84]
Following the instructions provided, I was able to train my own dataset (by modifying the VOC2007) with the ff. command:
`python ./faster_rcnn/train_net.py --gpu 0 --imdb voc_2007_trainval --iters 10 --cfg ./experiments/cfgs/faster_rcnn_end2end_resnet.yml --network VGGnet_train --restore 0 --set EXP_DIR exp_dir`

In order to test it, I'm using the ff. command:
`python ./faster_rcnn/test_net.py --gpu 0 --imdb voc_2007_trainval --cfg ./experiments/cfgs/faster_rcnn_end2end_resnet.yml --network VGGnet_train --weights output/exp_dir/voc_2007_trainval/Resnet50_iter_10.ckpt.meta`

Why is it that the test script can't seem to load my trained model? I've included the log below. 
Thank you.

**Configuration**
Tensorflow (GPU) = 1.0.1
Python = 2.7

**Log**

`W tensorflow/core/framework/op_kernel.cc:993] Data loss: Unable to open table file output/exp_dir/voc_2007_trainval/Resnet50_iter_10.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "./faster_rcnn/test_net.py", line 90, in <module>
    saver.restore(sess, args.model)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file output/exp_dir/voc_2007_trainval/Resnet50_iter_10.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_21 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_21/tensor_names, save/RestoreV2_21/shape_and_slices)]]
         [[Node: save/RestoreV2_16/_53 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_175_save/RestoreV2_16", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_21', defined at:
  File "./faster_rcnn/test_net.py", line 88, in <module>
    saver = tf.train.Saver()
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/xyzuser/.conda/envs/tf101gpu/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file output/exp_dir/voc_2007_trainval/Resnet50_iter_10.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_21 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_21/tensor_names, save/RestoreV2_21/shape_and_slices)]]
         [[Node: save/RestoreV2_16/_53 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_175_save/RestoreV2_16", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]`

**Comment by hqliling** [comment]
modify test script :--weights ./output/exp_dir/voc_2007_trainval/Resnet50_iter_10.ckpt 
and modify test_net.py like this:
https://github.com/smallcorgi/Faster-RCNN_TF/issues/157
finaly,it works.

**Comment by hqliling** [comment]
your test script has another dismatch place: Resnet50_iter_10.ckpt should be matched 'Resnet50_test', but  'VGGnet_train '

my [test_net.py](https://github.com/hqliling/TFFRCNN/blob/master/faster_rcnn/test_net.py)
