### ISSUE TITLE
one question about cpu and gpu

### ISSUE THREAD

**Issue by flyking1994** [CharlesShang/TFFRCNN#87]
E:/TFFRCNN
Traceback (most recent call last):
  File "E:\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\PyCharm Community Edition 2016.3.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/TFFRCNN/demo.py", line 12, in <module>
    from lib.networks.factory import get_network
  File "E:/TFFRCNN\lib\networks\__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "E:/TFFRCNN\lib\networks\VGGnet_train.py", line 2, in <module>
    from .network import Network
  File "E:/TFFRCNN\lib\networks\network.py", line 4, in <module>
    from ..fast_rcnn.config import cfg
  File "E:/TFFRCNN\lib\fast_rcnn\__init__.py", line 9, in <module>
    from . import train
  File "E:/TFFRCNN\lib\fast_rcnn\train.py", line 15, in <module>
    from .nms_wrapper import nms_wrapper
  File "E:/TFFRCNN\lib\fast_rcnn\nms_wrapper.py", line 11, in <module>
    from ..nms.cpu_nms import cpu_nms
ImportError: No module named 'lib.nms.cpu_nms'

**Comment by flyking1994** [comment]
there is also an error:ImportError: No module named 'lib.nms.gpu_nms'
are there some solutions?

**Comment by ShiJing123** [comment]
I also encountered the same problem at run time, I am also wrong in the compiler stage, I would like to know how to solve
